### ISSUE TITLE
Possibly replace List with NSTableView wrapper

### ISSUE THREAD

**Issue by ggoraa** [ggoraa/moc#32]
The reason for this change is simple: performance (and swipe actions)

Performance can be easily demonstrated here: https://kean.blog/post/not-list

And with swipe actions, they are available only on three-column `NavigationView` layout(idk why lol), but I don't have a `NavigationView`, it is replaced by a custom solution, so I lack swipe actions

Only benefits my people, only benefits

I think it will be implemented in 0.2.0 milestone release

**Comment by aiexz** [comment]
@ggoraa А свифте разве нет Lazy который показывает лишь часть?

**Comment by mishailovic** [comment]
@ggoraa А свифте разве нет Lazy который показывает лишь часть?

**Comment by ggoraa** [comment]
This will be not implemented. Too error-prone and unstable between OS releases. I hope Apple will add an option to disable automatic diffs described in a blog post above in macOS 13. If not, well, fuck me

**Comment by c-h3xcode** [comment]
@ggoraa we won't😳

**Comment by ggoraa** [comment]
> @ggoraa we won't😳

Thanks 😳
