### ISSUE TITLE
add to brew ?

### ISSUE THREAD

**Issue by theotheroracle** [ggoraa/moc#54]
do you have plans to add moc to brew.sh ? presumably a bit further in development, do you have a mvp ?

**Comment by ggoraa** [comment]
Hi!

Yes, I do plan adding Moc to brew, I just do some final preparations and bug fixes. After that, the Moc cask will be available in homebrew, ready for download!

**Comment by theotheroracle** [comment]
also, @c-h3xcode in case it's not obvious, this app wouldn't run on linux

**Comment by ggoraa** [comment]
> also, @c-h3xcode in case it's not obvious, this app wouldn't run on linux

It was a joke lol

**Comment by theotheroracle** [comment]
oh ok, my bad

**Comment by ggoraa** [comment]
Done! Released!

Look at the latest release, installation command can be found there
